<a href="https://colab.research.google.com/github/Kishankumar1328/CO2-EMMISION-Multiple-linear-Regression-/blob/main/CO2_EMMISION(Multiple_linear_Regression).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import  pylab as pl
import numpy as np
from sklearn.linear_model import LinearRegression
%matplotlib inline

In [ ]:
d=pd.read_csv("/content/CO2 Emissions_Canada.csv")
d

Make        Model   Vehicle Class  Engine Size(L)  Cylinders  \
0     ACURA          ILX         COMPACT             2.0          4   
1     ACURA          ILX         COMPACT             2.4          4   
2     ACURA   ILX HYBRID         COMPACT             1.5          4   
3     ACURA      MDX 4WD     SUV - SMALL             3.5          6   
4     ACURA      RDX AWD     SUV - SMALL             3.5          6   
...     ...          ...             ...             ...        ...   
7380  VOLVO  XC40 T5 AWD     SUV - SMALL             2.0          4   
7381  VOLVO  XC60 T5 AWD     SUV - SMALL             2.0          4   
7382  VOLVO  XC60 T6 AWD     SUV - SMALL             2.0          4   
7383  VOLVO  XC90 T5 AWD  SUV - STANDARD             2.0          4   
7384  VOLVO  XC90 T6 AWD  SUV - STANDARD             2.0          4   

     Transmission Fuel Type  Fuel Consumption City (L/100 km)  \
0             AS5         Z                               9.9   
1              M6         Z                              11.2   
2             AV7         Z                               6.0   
3             AS6         Z                              12.7   
4             AS6         Z                              12.1   
...           ...       ...                               ...   
7380          AS8         Z                              10.7   
7381          AS8         Z                              11.2   
7382          AS8         Z                              11.7   
7383          AS8         Z                              11.2   
7384          AS8         Z                              12.2   

      Fuel Consumption Hwy (L/100 km)  Fuel Consumption Comb (L/100 km)  \
0                                 6.7                               8.5   
1                                 7.7                               9.6   
2                                 5.8                               5.9   
3                                 9.1                              11.1   
4                                 8.7                              10.6   
...                               ...                               ...   
7380                              7.7                               9.4   
7381                              8.3                               9.9   
7382                              8.6                              10.3   
7383                              8.3                               9.9   
7384                              8.7                              10.7   

      Fuel Consumption Comb (mpg)  CO2 Emissions(g/km)  
0                              33                  196  
1                              29                  221  
2                              48                  136  
3                              25                  255  
4                              27                  244  
...                           ...                  ...  
7380                           30                  219  
7381                           29                  232  
7382                           27                  240  
7383                           29                  232  
7384                           26                  248  

[7385 rows x 12 columns]

In [ ]:
d.shape

(7385, 12)

In [ ]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7385 entries, 0 to 7384
Data columns (total 12 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   Make                              7385 non-null   object 
 1   Model                             7385 non-null   object 
 2   Vehicle Class                     7385 non-null   object 
 3   Engine Size(L)                    7385 non-null   float64
 4   Cylinders                         7385 non-null   int64  
 5   Transmission                      7385 non-null   object 
 6   Fuel Type                         7385 non-null   object 
 7   Fuel Consumption City (L/100 km)  7385 non-null   float64
 8   Fuel Consumption Hwy (L/100 km)   7385 non-null   float64
 9   Fuel Consumption Comb (L/100 km)  7385 non-null   float64
 10  Fuel Consumption Comb (mpg)       7385 non-null   int64  
 11  CO2 Emissions(g/km)               7385 non-null   int64  
dtypes: flo

In [ ]:
d.isnull()

Make  Model  Vehicle Class  Engine Size(L)  Cylinders  Transmission  \
0     False  False          False           False      False         False   
1     False  False          False           False      False         False   
2     False  False          False           False      False         False   
3     False  False          False           False      False         False   
4     False  False          False           False      False         False   
...     ...    ...            ...             ...        ...           ...   
7380  False  False          False           False      False         False   
7381  False  False          False           False      False         False   
7382  False  False          False           False      False         False   
7383  False  False          False           False      False         False   
7384  False  False          False           False      False         False   

      Fuel Type  Fuel Consumption City (L/100 km)  \
0         False                             False   
1         False                             False   
2         False                             False   
3         False                             False   
4         False                             False   
...         ...                               ...   
7380      False                             False   
7381      False                             False   
7382      False                             False   
7383      False                             False   
7384      False                             False   

      Fuel Consumption Hwy (L/100 km)  Fuel Consumption Comb (L/100 km)  \
0                               False                             False   
1                               False                             False   
2                               False                             False   
3                               False                             False   
4                               False                             False   
...                               ...                               ...   
7380                            False                             False   
7381                            False                             False   
7382                            False                             False   
7383                            False                             False   
7384                            False                             False   

      Fuel Consumption Comb (mpg)  CO2 Emissions(g/km)  
0                           False                False  
1                           False                False  
2                           False                False  
3                           False                False  
4                           False                False  
...                           ...                  ...  
7380                        False                False  
7381                        False                False  
7382                        False                False  
7383                        False                False  
7384                        False                False  

[7385 rows x 12 columns]

In [ ]:
d.describe()

Engine Size(L)    Cylinders  Fuel Consumption City (L/100 km)  \
count     7385.000000  7385.000000                       7385.000000   
mean         3.160068     5.615030                         12.556534   
std          1.354170     1.828307                          3.500274   
min          0.900000     3.000000                          4.200000   
25%          2.000000     4.000000                         10.100000   
50%          3.000000     6.000000                         12.100000   
75%          3.700000     6.000000                         14.600000   
max          8.400000    16.000000                         30.600000   

       Fuel Consumption Hwy (L/100 km)  Fuel Consumption Comb (L/100 km)  \
count                      7385.000000                       7385.000000   
mean                          9.041706                         10.975071   
std                           2.224456                          2.892506   
min                           4.000000                          4.100000   
25%                           7.500000                          8.900000   
50%                           8.700000                         10.600000   
75%                          10.200000                         12.600000   
max                          20.600000                         26.100000   

       Fuel Consumption Comb (mpg)  CO2 Emissions(g/km)  
count                  7385.000000          7385.000000  
mean                     27.481652           250.584699  
std                       7.231879            58.512679  
min                      11.000000            96.000000  
25%                      22.000000           208.000000  
50%                      27.000000           246.000000  
75%                      32.000000           288.000000  
max                      69.000000           522.000000

In [ ]:
df=d[["Engine Size(L)","Cylinders","Fuel Consumption Comb (mpg)","CO2 Emissions(g/km)"]]
df.head(29)

Engine Size(L)  Cylinders  Fuel Consumption Comb (mpg)  \
0              2.0          4                           33   
1              2.4          4                           29   
2              1.5          4                           48   
3              3.5          6                           25   
4              3.5          6                           27   
5              3.5          6                           28   
6              3.5          6                           28   
7              3.7          6                           25   
8              3.7          6                           24   
9              2.4          4                           31   
10             2.4          4                           29   
11             3.5          6                           27   
12             1.8          4                           34   
13             5.9         12                           18   
14             5.9         12                           18   
15             4.7          8                           19   
16             4.7          8                           18   
17             4.7          8                           19   
18             4.7          8                           18   
19             5.9         12                           18   
20             2.0          4                           32   
21             2.0          4                           28   
22             2.0          4                           30   
23             2.0          4                           28   
24             2.0          4                           28   
25             2.0          4                           30   
26             2.0          4                           28   
27             3.0          6                           26   
28             3.0          6                           35   

    CO2 Emissions(g/km)  
0                   196  
1                   221  
2                   136  
3                   255  
4                   244  
5                   230  
6                   232  
7                   255  
8                   267  
9                   212  
10                  225  
11                  239  
12                  193  
13                  359  
14                  359  
15                  338  
16                  354  
17                  338  
18                  354  
19                  359  
20                  202  
21                  230  
22                  214  
23                  230  
24                  230  
25                  214  
26                  235  
27                  251  
28                  217

In [ ]:
msk=np.random.rand(len(df))<0.8
train=df[msk]
test=df[~msk]

In [ ]:
lm=LinearRegression()


In [ ]:
x=np.asanyarray(train[["Engine Size(L)","Cylinders","Fuel Consumption Comb (mpg)"]])

In [ ]:
y=np.asanyarray(train["CO2 Emissions(g/km)"])

In [ ]:
lm.fit(x,y)

LinearRegression()

In [ ]:
lm.coef_

array([ 7.01620562,  7.94897432, -4.88898458])

In [ ]:
lm.intercept_

318.17668340538097

# ***`PREDICTION`***

In [ ]:
y_hat=lm.predict(test[["Engine Size(L)","Cylinders","Fuel Consumption Comb (mpg)"]])
x=np.asanyarray(test[["Engine Size(L)","Cylinders","Fuel Consumption Comb (mpg)"]])
y=np.asanyarray(test[["CO2 Emissions(g/km)"]])


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


In [ ]:
y_hat

array([225.03092148, 268.20263461, 269.60587573, ..., 217.33545466,
       222.22443923, 236.89139296])

In [ ]:
x

array([[ 2.4,  4. , 29. ],
       [ 3.5,  6. , 25. ],
       [ 3.7,  6. , 25. ],
       ...,
       [ 2. ,  4. , 30. ],
       [ 2. ,  4. , 29. ],
       [ 2. ,  4. , 26. ]])

In [ ]:
y

array([[221],
       [255],
       [255],
       ...,
       [219],
       [232],
       [248]])

In [ ]:
print("Mean Square Error:%.2f"%np.mean((y_hat-y)**2))

Mean Square Error:6476.17


In [ ]:
print("Variance score:%.2f"%lm.score(x,y))

Variance score:0.90


In [ ]:
lm=LinearRegression()
x=np.asanyarray(train[["Engine Size(L)","Cylinders","Fuel Consumption Comb (mpg)"]])
y=np.asanyarray(train[["CO2 Emissions(g/km)"]])
lm.fit(x,y)

LinearRegression()

In [ ]:
lm.coef_

array([[ 7.01620562,  7.94897432, -4.88898458]])

In [ ]:
y_=lm.predict(test[["Engine Size(L)","Cylinders","Fuel Consumption Comb (mpg)"]])
x=np.asanyarray(test[["Engine Size(L)","Cylinders","Fuel Consumption Comb (mpg)"]])
y=np.asanyarray(test[["CO2 Emissions(g/km)"]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


In [ ]:
print("Residual sum of square(MSE):%.2f"%np.mean(y_-y)**2)

Residual sum of square(MSE):0.04


In [ ]:
print("Variance score:%.2f"%lm.score(x,y))

Variance score:0.90
